n_jobs: 8 # Threads

names: ['parse', '10x']

count_adata:
  parse:
    /Users/nargesrezaie/Documents/MortazaviLab/Topyfic/workflow/snakemake/resources/Bridge_LeftCortex_Parse_harmony_annotated_Topyfic_regGene.h5ad
  10x:
    /Users/nargesrezaie/Documents/MortazaviLab/Topyfic/workflow/snakemake/resources/Bridge_LeftCortex_10x_harmony_annotated_Topyfic_regGene.h5ad

n_topics: [5, 10] #, 15, 20, 25, 30, 35, 40, 45, 50]

organism: mouse # human or mouse

workdir: /Users/nargesrezaie/Documents/MortazaviLab/Topyfic/workflow/snakemake/results/

train:
  n_runs: 100
  random_states: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                  10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                  20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                  30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
                  40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                  50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
                  60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
                  70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
                  80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                  90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

top_model:
  n_top_genes: 50
  resolution: 1
  max_iter_harmony: 10
  min_cell_participation: None

merge: True
